[package]
name = "cch23-aoc-distraction"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.2"
serde = {version = "1.0.193", features = ["derive"]}
serde_json = "1.0.108"
shuttle-axum = { version = "0.35.2"}
shuttle-runtime = "0.35.2"
tokio = "1.28.2"
tracing = "0.1.40"
